<a href="https://colab.research.google.com/github/rampselv/dataanalytics/blob/master/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam 
import numpy as np


In [0]:
input = np.array([[1,0,1]])
print(input)
output = np.array([[1,0]])
print(output)

[[1 0 1]]
[[1 0]]


In [0]:
model = Sequential()
#Add two hidden and one output layer
h1 = model.add(Dense(2,activation="sigmoid",input_dim=3))
h2=model.add(Dense(3,activation="sigmoid"))
o = model.add(Dense(2,activation='sigmoid'))

W0827 10:06:21.201775 140617367029632 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0827 10:06:21.246906 140617367029632 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0827 10:06:21.255689 140617367029632 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [0]:
#initial weights
model.layers[0].get_weights()

W0827 06:29:27.352648 140023925626752 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0827 06:29:27.357496 140023925626752 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



[array([[ 0.05028677, -0.5777493 ],
        [-0.66406226,  1.017664  ],
        [-1.050328  ,  0.18597972]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [0]:
wlayer1= np.array([[0.2,-0.3],[0.4,0.1],[-0.5,0.2]])
wbias = np.array([-0.4,.2])
li=[]
li.append(wlayer1)
li.append(wbias)
model.layers[0].set_weights(li) 

In [0]:
wlayer2= np.array([[-0.3,0.2,0.6],[-0.2,-0.1,-0.2]])
wbias2= np.array([0.1,0.1,0.2])
li=  []
li.append(wlayer2)
li.append(wbias2)
model.layers[1].set_weights(li)

In [0]:
wlayer3= np.array([[0.3,0.2],[-0.5,0.5],[-0.7,0.2]])
wbias3= np.array([0.1,0.2])
li=  []
li.append(wlayer3)
li.append(wbias3)
model.layers[2].set_weights(li) 

In [0]:
model.compile(loss="mean_squared_error",optimizer=Adam(lr=.9),metrics=['accuracy'])
model.summary()

W0827 10:18:52.408755 140617367029632 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 2)                 8         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 9         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 8         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.fit(input,output,batch_size=1,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.4019 - acc: 0.0000e+00
Epoch 2/50
 - 0s - loss: 0.0530 - acc: 1.0000
Epoch 3/50
 - 0s - loss: 0.0027 - acc: 1.0000
Epoch 4/50
 - 0s - loss: 2.7966e-04 - acc: 1.0000
Epoch 5/50
 - 0s - loss: 4.1806e-05 - acc: 1.0000
Epoch 6/50
 - 0s - loss: 8.1709e-06 - acc: 1.0000
Epoch 7/50
 - 0s - loss: 1.9699e-06 - acc: 1.0000
Epoch 8/50
 - 0s - loss: 5.6338e-07 - acc: 1.0000
Epoch 9/50
 - 0s - loss: 1.8586e-07 - acc: 1.0000
Epoch 10/50
 - 0s - loss: 6.9216e-08 - acc: 1.0000
Epoch 11/50
 - 0s - loss: 2.8624e-08 - acc: 1.0000
Epoch 12/50
 - 0s - loss: 1.2962e-08 - acc: 1.0000
Epoch 13/50
 - 0s - loss: 6.3613e-09 - acc: 1.0000
Epoch 14/50
 - 0s - loss: 3.3431e-09 - acc: 1.0000
Epoch 15/50
 - 0s - loss: 1.8689e-09 - acc: 1.0000
Epoch 16/50
 - 0s - loss: 1.1052e-09 - acc: 1.0000
Epoch 17/50
 - 0s - loss: 6.8823e-10 - acc: 1.0000
Epoch 18/50
 - 0s - loss: 4.4584e-10 - acc: 1.0000
Epoch 19/50
 - 0s - loss: 3.0182e-10 - acc: 1.0000
Epoch 20/50
 - 0s - loss: 2.1257e-10 - acc: 1.00

In [0]:
print(model.layers[0].get_weights())
print(model.layers[1].get_weights())
print(model.layers[2].get_weights())


[array([[-4.76151  ,  4.4430275],
       [ 0.4      ,  0.1      ],
       [-5.4615107,  4.943028 ]], dtype=float32), array([-5.3615103,  4.943028 ], dtype=float32)]
[array([[ 6.444714 , -4.7905855, -4.323098 ],
       [ 6.3956842, -4.52126  , -3.927562 ]], dtype=float32), array([ 7.06991  , -4.589737 , -4.0928087], dtype=float32)]
[array([[ 6.6167607, -6.947487 ],
       [ 4.897478 , -5.248495 ],
       [ 4.6810975, -5.5177693]], dtype=float32), array([ 5.9778624, -6.384845 ], dtype=float32)]


In [0]:
newoutput= model.predict(input)
print(newoutput)

[[9.9999666e-01 1.6173582e-06]]
